package com.example.feature_c

import com.example.feature_laucnher_api.FeatureLauncherApi

@com.example.navigation_annotation.FeatureLauncherApiAnnotation
interface FeatureCLauncher : FeatureLauncherApi