package com.example.feature_c

import com.example.feature_laucnher_api.FeatureLauncherApi
import com.example.navigation_annotation.FeatureLauncherApiAnnotation

@FeatureLauncherApiAnnotation
interface FeatureCLauncher : FeatureLauncherApi