package com.example.feature_b

import com.example.feature_laucnher_api.FeatureLauncherApi

@com.example.navigation_annotation.FeatureLauncherApiAnnotation
interface FeatureBLauncher : FeatureLauncherApi