package com.example.feature_b

import com.example.feature_laucnher_api.FeatureLauncherApi
import com.example.navigation_annotation.FeatureLauncherApiAnnotation

@FeatureLauncherApiAnnotation
interface FeatureBLauncher : FeatureLauncherApi